import type { BlockId } from "@/lib/project-schema";
import { element as h, text, type HtmlNode } from "@/lib/templates/html";
import { articlePreviewStyles, articleStyles } from "@/lib/templates/article-styles";
import type { BlockDefinition, FieldDefinition, TemplateDefinition, TemplateRenderContext } from "@/lib/templates/types";

const blocks: readonly BlockDefinition[] = [
  { id: "article-header", label: "Article header", movable: true }, { id: "hero-media", label: "Hero media", movable: true }, { id: "notice-cta", label: "Reader notice", movable: true }, { id: "overview", label: "Feature overview", movable: true }, { id: "feature-panel", label: "Key points panel", movable: true }, { id: "walkthrough", label: "Walkthrough", movable: true }, { id: "case-study", label: "Reader perspective", movable: true }, { id: "registration-form", label: "Information form", movable: true }, { id: "closing-cta", label: "Closing call to action", movable: true }, { id: "comments", label: "Reader comments", movable: true },
];
const field = (blockId: BlockId, id: string, label: string, defaultValue: string, kind: "input" | "textarea" = "input"): FieldDefinition => ({ blockId, id, label, defaultValue, kind });
const fields: readonly FieldDefinition[] = [
  field("article-header", "category", "Category", "Technology & society"), field("article-header", "headline", "Headline", "How digital tools are changing everyday research", "textarea"), field("article-header", "dek", "Summary", "A practical look at how people evaluate new services, ask better questions, and make informed choices.", "textarea"), field("article-header", "byline", "Byline", "By the Editorial Desk"), field("article-header", "date", "Publication date", "May 2026"),
  field("hero-media", "hero-media-label", "Image placeholder label", "Editorial feature image"), field("notice-cta", "notice-title", "Notice heading", "A note for readers"), field("notice-cta", "notice-copy", "Notice copy", "This is a static editorial template. Review information carefully and use independent sources before making a decision.", "textarea"), field("notice-cta", "notice-cta", "Button label", "Read the guide"),
  field("overview", "overview-title", "Heading", "A clearer way to assess new tools"), field("overview", "overview-copy", "Body", "Useful services explain what they do, who they are for, and where their limits are. Start with the basics, compare reliable sources, and take the time you need to decide.", "textarea"),
  field("feature-panel", "panel-title", "Panel heading", "Questions worth asking"), field("feature-panel", "panel-copy", "Panel introduction", "Keep a record of the questions that matter most to you.", "textarea"), field("feature-panel", "stat-one", "Point 1", "Purpose"), field("feature-panel", "stat-two", "Point 2", "Evidence"), field("feature-panel", "stat-three", "Point 3", "Next step"),
  field("walkthrough", "walkthrough-title", "Heading", "A simple research process"), field("walkthrough", "step-one", "Step 1", "Identify the information you need"), field("walkthrough", "step-two", "Step 2", "Compare independent sources"), field("walkthrough", "step-three", "Step 3", "Decide at your own pace"),
  field("case-study", "perspective-title", "Heading", "A reader perspective"), field("case-study", "perspective-copy", "Body", "“I found it helpful to pause, list my questions, and look for information from more than one source before taking the next step.”", "textarea"),
  field("registration-form", "form-title", "Heading", "Request more information"), field("registration-form", "form-copy", "Description", "This visual-only form shows where a future contact flow could appear. It does not send or store visitor details.", "textarea"), field("registration-form", "form-name", "Name label", "Name"), field("registration-form", "form-email", "Email label", "Email address"), field("registration-form", "form-phone", "Phone label", "Phone number"), field("registration-form", "form-topic", "Topic label", "Topic of interest"), field("registration-form", "form-submit", "Button label", "Request information"), field("registration-form", "form-note", "Consent note", "Preview only — no information is submitted or stored.", "textarea"),
  field("closing-cta", "closing-title", "Heading", "Keep exploring with context"), field("closing-cta", "closing-copy", "Body", "Save your questions, return to the sources you trust, and choose a next step when you are ready.", "textarea"), field("closing-cta", "closing-cta", "Button label", "View information form"),
  ...[1, 2, 3].flatMap((index) => [field("comments", `comment-${index}-name`, `Comment ${index} name`, ["Rafa M.", "Joana P.", "Cris L."][index - 1]), field("comments", `comment-${index}-body`, `Comment ${index} text`, ["Clear examples made the topic easier to understand.", "I appreciated the reminder to check more than one source.", "The step-by-step questions are a useful starting point."][index - 1], "textarea")]),
];
const value = (context: TemplateRenderContext, id: string) => context.value(id);
const block = (id: BlockId, context: TemplateRenderContext, children: HtmlNode[]) => h("section", { id, class: `news-block${context.documentMode === "preview" && context.previewFocusedBlockId === id ? " preview-focused" : ""}`, ...(context.documentMode === "preview" ? { "data-block-id": id } : {}) }, children);
const copy = (content: string) => h("p", { class: "news-copy" }, [text(content)]);
const points = (context: TemplateRenderContext, keys: string[]) => h("div", { class: "stat-grid" }, keys.map((key) => h("div", { class: "stat" }, [h("strong", {}, [text(value(context, key))]), h("span", {}, [text("Consider this")])])));
function renderBlock(id: BlockId, context: TemplateRenderContext): HtmlNode {
  switch (id) {
    case "article-header": return block(id, context, [h("div", { class: "article-kicker" }, [text(value(context, "category"))]), h("h1", {}, [text(value(context, "headline"))]), h("p", { class: "article-dek" }, [text(value(context, "dek"))]), h("p", { class: "byline" }, [text(`${value(context, "byline")} · ${value(context, "date")}`)])]);
    case "hero-media": return block(id, context, [h("div", { class: "media-placeholder", role: "img", "aria-label": value(context, "hero-media-label") }, [h("div", {}, [text(value(context, "hero-media-label")), h("small", {}, [text("Image placeholder")])])])]);
    case "notice-cta": return block(id, context, [h("div", { class: "notice" }, [h("h2", {}, [text(value(context, "notice-title"))]), h("p", {}, [text(value(context, "notice-copy"))]), h("a", { class: "article-button", href: "#registration-form" }, [text(value(context, "notice-cta"))])])]);
    case "overview": return block(id, context, [h("h2", {}, [text(value(context, "overview-title"))]), copy(value(context, "overview-copy"))]);
    case "feature-panel": return block(id, context, [h("div", { class: "panel" }, [h("h2", {}, [text(value(context, "panel-title"))]), copy(value(context, "panel-copy")), points(context, ["stat-one", "stat-two", "stat-three"])])]);
    case "walkthrough": return block(id, context, [h("h2", {}, [text(value(context, "walkthrough-title"))]), h("div", { class: "steps" }, ["step-one", "step-two", "step-three"].map((key) => h("div", { class: "step" }, [text(value(context, key))])))]);
    case "case-study": return block(id, context, [h("h2", {}, [text(value(context, "perspective-title"))]), copy(value(context, "perspective-copy"))]);
    case "registration-form": return block(id, context, [h("div", { class: "form-card" }, [h("h2", {}, [text(value(context, "form-title"))]), h("p", {}, [text(value(context, "form-copy"))]), h("form", { "aria-label": "Visual-only information form" }, [h("div", { class: "form-grid" }, ["name", "email", "phone", "topic"].map((key) => h("label", {}, [text(value(context, `form-${key}`)), h("input", { disabled: true, type: key === "email" ? "email" : key === "phone" ? "tel" : "text", placeholder: value(context, `form-${key}`) })]))), h("button", { type: "button", disabled: true }, [text(value(context, "form-submit"))])]), h("p", { class: "form-note" }, [text(value(context, "form-note"))])])]);
    case "closing-cta": return block(id, context, [h("div", { class: "notice" }, [h("h2", {}, [text(value(context, "closing-title"))]), h("p", {}, [text(value(context, "closing-copy"))]), h("a", { class: "article-button", href: "#registration-form" }, [text(value(context, "closing-cta"))])])]);
    case "comments": return block(id, context, [h("div", { class: "comments" }, [h("h2", {}, [text("Reader comments")]), ...[1, 2, 3].map((index) => h("article", { class: "comment" }, [h("p", { class: "comment-name" }, [text(value(context, `comment-${index}-name`))]), h("p", {}, [text(value(context, `comment-${index}-body`))])]))])]);
    default: throw new Error(`Unknown article block: ${id}`);
  }
}
export const article3035Template: TemplateDefinition = { id: "article-3035", name: "Editorial Article 3035", description: "A magazine-style editorial article with a related-stories sidebar.", blocks, defaultBlockOrder: blocks.map((entry) => entry.id), fields, stylesheet: articleStyles("#b20f2e", "#f5d9df", true), previewStylesheet: articlePreviewStyles, renderBlock, renderDocument: (_context, pageBlocks) => h("div", { class: "news-shell" }, [h("header", { class: "news-topbar" }, [h("div", { class: "news-topbar-inner" }, [h("span", { class: "news-brand" }, [text("JOURNAL")]), h("span", { class: "news-section" }, [text("Insights")]), h("span", { class: "news-menu" }, [text("Latest · Topics · About")])])]), h("div", { class: "news-layout" }, [h("main", { class: "news-article" }, pageBlocks), h("aside", { class: "news-aside", "aria-label": "Related stories" }, [h("h2", {}, [text("Most read")]), ...["How to spot useful product information", "A practical checklist for comparing sources", "Making room for better questions"].map((item) => h("div", { class: "related-item" }, [text(item)]))])]), h("footer", { class: "news-footer" }, [h("div", { class: "news-footer-inner" }, [h("strong", {}, [text("JOURNAL")]), h("p", {}, [text("A static editorial template for demonstration purposes.")])])])]) };
