export function articleStyles(accent: string, mutedAccent: string, sidebar = false) {
  return `
    :root { color-scheme: light; --accent:${accent}; --muted-accent:${mutedAccent}; --ink:#172033; --muted:#5f6878; --line:#dce1e8; --paper:#fff; --wash:#f5f7fa; font-family:Arial,Helvetica,sans-serif; }
    * { box-sizing:border-box; } body { margin:0; background:var(--paper); color:var(--ink); } a { color:inherit; } button,input { font:inherit; }
    .news-shell { min-height:100vh; } .news-topbar { border-bottom:1px solid var(--line); background:#fff; } .news-topbar-inner { max-width:1160px; margin:auto; min-height:64px; padding:0 24px; display:flex; align-items:center; gap:20px; }
    .news-brand { color:var(--accent); font-size:23px; font-weight:800; letter-spacing:-1px; } .news-section { border-left:1px solid var(--line); padding-left:20px; font-weight:700; } .news-menu { margin-left:auto; color:var(--muted); font-size:14px; }
    .news-layout { max-width:1160px; margin:0 auto; padding:40px 24px 64px; display:grid; grid-template-columns:minmax(0,760px)${sidebar ? " minmax(230px,300px)" : ""}; gap:48px; } .news-article { min-width:0; }
    .news-block { margin:0 0 34px; scroll-margin-top:16px; } .article-kicker { color:var(--accent); font-size:13px; font-weight:800; letter-spacing:.08em; text-transform:uppercase; }
    h1,h2,h3,p { margin-top:0; } h1 { margin:10px 0 16px; font-family:Georgia,serif; font-size:clamp(34px,5vw,54px); line-height:1.04; letter-spacing:-.035em; } h2 { font-family:Georgia,serif; font-size:clamp(25px,3vw,34px); line-height:1.14; letter-spacing:-.02em; } h3 { font-size:18px; margin-bottom:8px; } .article-dek { font-size:20px; line-height:1.45; color:#424b5a; } .byline { color:var(--muted); font-size:14px; font-weight:600; }
    .media-placeholder { min-height:300px; display:grid; place-items:center; border-radius:6px; background:linear-gradient(135deg,var(--muted-accent),#e8edf4); color:#27364c; text-align:center; padding:24px; font-weight:700; } .media-placeholder small { display:block; margin-top:6px; font-weight:400; }
    .news-copy { font-family:Georgia,serif; font-size:19px; line-height:1.62; } .news-copy p + p { margin-top:16px; } .notice { border-left:5px solid var(--accent); background:var(--wash); padding:22px; } .notice p { margin-bottom:16px; font-size:17px; line-height:1.5; }
    .article-button { display:inline-block; border:0; border-radius:4px; background:var(--accent); color:#fff; padding:12px 18px; font-weight:800; text-decoration:none; } .panel { border:1px solid var(--line); border-radius:8px; padding:24px; background:#fff; } .stat-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:12px; margin-top:18px; } .stat { background:var(--wash); border-radius:6px; padding:16px; } .stat strong { display:block; color:var(--accent); font-size:22px; }
    .steps { display:grid; gap:14px; counter-reset:steps; } .step { position:relative; padding:18px 18px 18px 62px; border-top:1px solid var(--line); } .step:before { counter-increment:steps; content:counter(steps); position:absolute; left:12px; top:18px; color:var(--accent); font-weight:800; font-size:24px; }
    .form-card { border:1px solid var(--line); border-radius:8px; background:var(--wash); padding:28px; } .form-card h2 { margin-bottom:8px; } .form-grid { display:grid; grid-template-columns:repeat(2,minmax(0,1fr)); gap:14px; margin:20px 0; } .form-card label { display:grid; gap:6px; color:#3d4654; font-size:14px; font-weight:700; } .form-card input { width:100%; border:1px solid #cbd3df; border-radius:4px; padding:11px; background:#fff; color:#697386; } .form-card button { border:0; border-radius:4px; width:100%; padding:13px; background:#98a2b3; color:#fff; font-weight:800; } .form-note { margin:12px 0 0; color:var(--muted); font-size:13px; }
    .comments { border-top:3px solid var(--ink); padding-top:20px; } .comment { border-bottom:1px solid var(--line); padding:16px 0; } .comment-name { font-weight:800; margin-bottom:6px; } .comment p:last-child { margin:0; color:#404957; line-height:1.5; }
    .news-aside { border-left:1px solid var(--line); padding-left:24px; } .news-aside h2 { font-family:Arial,Helvetica,sans-serif; font-size:19px; } .related-item { border-top:1px solid var(--line); padding:14px 0; font-size:15px; font-weight:700; line-height:1.35; }
    .news-footer { background:#172033; color:#e8ecf3; } .news-footer-inner { max-width:1160px; margin:auto; padding:30px 24px; display:flex; justify-content:space-between; gap:24px; font-size:14px; } .news-footer strong { color:#fff; }
    @media (max-width:800px) { .news-layout { display:block; padding:28px 18px 48px; } .news-aside { border-left:0; border-top:1px solid var(--line); padding:28px 0 0; margin-top:30px; } .news-topbar-inner { padding:0 18px; } .news-menu { display:none; } .form-grid,.stat-grid { grid-template-columns:1fr; } .media-placeholder { min-height:220px; } .news-footer-inner { display:block; } .news-footer-inner p { margin-bottom:0; } }
  `;
}

export const articlePreviewStyles = ".news-block.preview-focused{outline:3px solid #3b82f6;outline-offset:8px;border-radius:4px;box-shadow:0 0 0 4px rgba(59,130,246,.18)}";
