import type { BlockId } from "@/lib/project-schema";
import { element as h, text, type HtmlNode } from "@/lib/templates/html";
import { articlePreviewStyles, articleStyles } from "@/lib/templates/article-styles";
import type { BlockDefinition, FieldDefinition, TemplateDefinition, TemplateRenderContext } from "@/lib/templates/types";

const blocks: readonly BlockDefinition[] = [
  { id: "article-header", label: "Article header", movable: true }, { id: "hero-media", label: "Hero media", movable: true }, { id: "editorial-intro", label: "Editorial introduction", movable: true }, { id: "explainer", label: "Explainer", movable: true }, { id: "eligibility", label: "Who this is for", movable: true }, { id: "safety-note", label: "Safety note", movable: true }, { id: "pricing-context", label: "Cost context", movable: true }, { id: "illustration", label: "Illustrative panel", movable: true }, { id: "registration-form", label: "Information form", movable: true }, { id: "comments", label: "Reader comments", movable: true },
];
const field = (blockId: BlockId, id: string, label: string, defaultValue: string, kind: "input" | "textarea" = "input"): FieldDefinition => ({ blockId, id, label, defaultValue, kind });
const fields: readonly FieldDefinition[] = [
  field("article-header", "category", "Category", "Public interest"), field("article-header", "headline", "Headline", "A closer look at a service people are curious about", "textarea"), field("article-header", "dek", "Summary", "An editorial explainer about understanding options, reading the details, and deciding with care.", "textarea"), field("article-header", "byline", "Byline", "By the Newsroom"), field("article-header", "date", "Publication date", "May 2026"),
  field("hero-media", "hero-media-label", "Image placeholder label", "Report image"), field("editorial-intro", "intro-title", "Heading", "Start with the information in front of you"), field("editorial-intro", "intro-copy", "Body", "Good decisions rarely need to be rushed. Begin by understanding the service, its intended audience, and the questions it does not answer.", "textarea"),
  field("explainer", "explainer-title", "Heading", "What to look for in an explanation"), field("explainer", "explainer-copy", "Body", "Look for plain language, verifiable sources, and clear distinctions between facts, examples, and opinions. If something matters, take time to check it independently.", "textarea"), field("explainer", "explainer-cta", "Button label", "Request information"),
  field("eligibility", "eligibility-title", "Heading", "Who may find this useful"), field("eligibility", "eligibility-copy", "Body", "This layout is designed for readers who want an organized starting point. It is not a recommendation or a promise about any outcome.", "textarea"),
  field("safety-note", "safety-title", "Heading", "Keep safety in the conversation"), field("safety-note", "safety-copy", "Body", "Do not share personal information until you understand why it is requested, how it will be handled, and what alternatives are available.", "textarea"),
  field("pricing-context", "pricing-title", "Heading", "Understand the full cost context"), field("pricing-context", "pricing-copy", "Body", "Ask for a clear description of fees, limitations, cancellation terms, and any conditions that could affect your experience.", "textarea"),
  field("illustration", "illustration-title", "Panel heading", "A practical checklist"), field("illustration", "illustration-one", "Point 1", "Read the details"), field("illustration", "illustration-two", "Point 2", "Compare sources"), field("illustration", "illustration-three", "Point 3", "Ask questions"),
  field("registration-form", "form-title", "Heading", "Ask for more information"), field("registration-form", "form-copy", "Description", "This preview form is visual only. It does not collect, transmit, or retain information.", "textarea"), field("registration-form", "form-name", "Name label", "Name"), field("registration-form", "form-email", "Email label", "Email address"), field("registration-form", "form-phone", "Phone label", "Phone number"), field("registration-form", "form-topic", "Topic label", "Question or topic"), field("registration-form", "form-submit", "Button label", "Send request"), field("registration-form", "form-note", "Consent note", "Preview only — no details are sent or stored.", "textarea"),
  ...[1, 2, 3].flatMap((index) => [field("comments", `comment-${index}-name`, `Comment ${index} name`, ["Ana S.", "Marcos V.", "Bia R."][index - 1]), field("comments", `comment-${index}-body`, `Comment ${index} text`, ["The checklist helped me organize what to research.", "It is useful to see the safety questions stated clearly.", "I like having a simple way to compare information."][index - 1], "textarea")]),
];
const value = (context: TemplateRenderContext, id: string) => context.value(id);
const block = (id: BlockId, context: TemplateRenderContext, children: HtmlNode[]) => h("section", { id, class: `news-block${context.documentMode === "preview" && context.previewFocusedBlockId === id ? " preview-focused" : ""}`, ...(context.documentMode === "preview" ? { "data-block-id": id } : {}) }, children);
const prose = (title: string, content: string) => [h("h2", {}, [text(title)]), h("p", { class: "news-copy" }, [text(content)])];
const checklist = (context: TemplateRenderContext) => h("div", { class: "stat-grid" }, ["illustration-one", "illustration-two", "illustration-three"].map((key) => h("div", { class: "stat" }, [h("strong", {}, [text(value(context, key))]), h("span", {}, [text("Checklist item")])])));
function renderBlock(id: BlockId, context: TemplateRenderContext): HtmlNode {
  switch (id) {
    case "article-header": return block(id, context, [h("div", { class: "article-kicker" }, [text(value(context, "category"))]), h("h1", {}, [text(value(context, "headline"))]), h("p", { class: "article-dek" }, [text(value(context, "dek"))]), h("p", { class: "byline" }, [text(`${value(context, "byline")} · ${value(context, "date")}`)])]);
    case "hero-media": return block(id, context, [h("div", { class: "media-placeholder", role: "img", "aria-label": value(context, "hero-media-label") }, [h("div", {}, [text(value(context, "hero-media-label")), h("small", {}, [text("Image placeholder")])])])]);
    case "editorial-intro": return block(id, context, prose(value(context, "intro-title"), value(context, "intro-copy")));
    case "explainer": return block(id, context, [...prose(value(context, "explainer-title"), value(context, "explainer-copy")), h("a", { class: "article-button", href: "#registration-form" }, [text(value(context, "explainer-cta"))])]);
    case "eligibility": return block(id, context, prose(value(context, "eligibility-title"), value(context, "eligibility-copy")));
    case "safety-note": return block(id, context, [h("div", { class: "notice" }, prose(value(context, "safety-title"), value(context, "safety-copy"))) ]);
    case "pricing-context": return block(id, context, prose(value(context, "pricing-title"), value(context, "pricing-copy")));
    case "illustration": return block(id, context, [h("div", { class: "panel" }, [h("h2", {}, [text(value(context, "illustration-title"))]), checklist(context)])]);
    case "registration-form": return block(id, context, [h("div", { class: "form-card" }, [h("h2", {}, [text(value(context, "form-title"))]), h("p", {}, [text(value(context, "form-copy"))]), h("form", { "aria-label": "Visual-only information form" }, [h("div", { class: "form-grid" }, ["name", "email", "phone", "topic"].map((key) => h("label", {}, [text(value(context, `form-${key}`)), h("input", { disabled: true, type: key === "email" ? "email" : key === "phone" ? "tel" : "text", placeholder: value(context, `form-${key}`) })]))), h("button", { type: "button", disabled: true }, [text(value(context, "form-submit"))])]), h("p", { class: "form-note" }, [text(value(context, "form-note"))])])]);
    case "comments": return block(id, context, [h("div", { class: "comments" }, [h("h2", {}, [text("Reader comments")]), ...[1, 2, 3].map((index) => h("article", { class: "comment" }, [h("p", { class: "comment-name" }, [text(value(context, `comment-${index}-name`))]), h("p", {}, [text(value(context, `comment-${index}-body`))])]))])]);
    default: throw new Error(`Unknown article block: ${id}`);
  }
}
export const article2975Template: TemplateDefinition = { id: "article-2975", name: "Editorial Article 2975", description: "A focused news-style explainer with guided editorial sections.", blocks, defaultBlockOrder: blocks.map((entry) => entry.id), fields, stylesheet: articleStyles("#c4170c", "#f9dedb"), previewStylesheet: articlePreviewStyles, renderBlock, renderDocument: (_context, pageBlocks) => h("div", { class: "news-shell" }, [h("header", { class: "news-topbar" }, [h("div", { class: "news-topbar-inner" }, [h("span", { class: "news-brand" }, [text("DAILY")]), h("span", { class: "news-section" }, [text("News")]), h("span", { class: "news-menu" }, [text("Home · Topics · Contact")])])]), h("div", { class: "news-layout" }, [h("main", { class: "news-article" }, pageBlocks)]), h("footer", { class: "news-footer" }, [h("div", { class: "news-footer-inner" }, [h("strong", {}, [text("DAILY NEWS")]), h("p", {}, [text("A static editorial template for demonstration purposes.")])])])]) };
